eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
      
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
    
  zipkin:
    base-url: http://192.168.99.100:9411/  
  
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
      
logging:
  level:
    com.ibm.productservice: TRACE
    org.springframework: INFO
   